sudo: required
services:
    - docker

before_install:
    - docker build -t mooreinteractive/5-docker-react -f Dockerfile.dev .

script:
    - docker run mooreinteractive/5-docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "5-docker-react"
    env: "5DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-314480548641"
    bucket_path: "5-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
