sudo: required
services:
    - docker

before_install:
    - docker build -t mooreinteractive/5-docker-react -f Dockerfile.dev .

script:
    - docker run mooreinteractive/5-docker-react npm run test -- --coverage
    
